<div class="large-12 columns"><br></div>
<?php if (!$this->loggedIn): ?>
 
    <?php if (isset($this->responseLogin)): ?>
       <small class="label label-danger"><?php echo $this->responseLogin; ?></span>
    <?php endif; ?>
<div class="large-4 large-offset-4 columns panel end">
<h3 class="text-center"><?php echo $this->titulo;?>  </h3>
<h6 class="text-center" ><?php echo $this->mensaje;?>  </h6>
    <?php
// within a view script
    $form = $this->form;
    $form->prepare();

    $form->setAttribute('action', $this->url('admin', array('controller' => 'login', 'action' => 'autenticar')));

    $form->setAttribute('method', 'post');

// Get the form label plugin
    $formLabel = $this->plugin('formLabel');

// Render the opening tag
    echo $this->form()->openTag($form);
    ?>
    <div class="form-group">
			<img src="<?php echo $this->basePath('assets/admin/layout/img/logo.png');?>" class="logo">
		</div>
		<h5 class="form-title">Inserisci i tuoi dati d'accesso</h5>
		<div class="alert alert-danger display-hide">
			<button class="close" data-close="alert"></button>
			<span>
			Inserisci tutti i dati richiesti.</span>
		</div>
    <div class="form-group">
			<?php 
			$email = $form->get('nome');
			echo $formLabel->openTag() . $email->getOption('label').$formLabel->closeTag();?>
			<div class="input-icon">
				<i class="fa fa-user"></i>
                <?php
                echo $this->formInput($email);
                echo $this->formElementErrors($email);
                ?>
            </div>
		</div>

    <div class="form-group">
        <?php
        $password = $form->get('password');
        echo $formLabel->openTag() . $password->getOption('label'). $formLabel->closeTag(); ?>
        <div class="input-icon">
				<i class="fa fa-pencil"></i>
      <?php  
        echo $this->formInput($password);
        echo $this->formElementErrors($password);
        ?></div>
        </div>

<br>

       
		
		<div class="form-group">
			<button type="submit" class="btn green-haze pull-right">
			<?php echo $this->formElement($form->get('send')) ?> <i class="m-icon-swapright m-icon-white"></i>
			</button>
		</div>
		



    

    <?php echo $this->form()->closeTag() ?>
</div> 
<?php endif; ?>