
        <div class="page-header navbar navbar-fixed-top">
        	<div class="page-header-inner">
        		<div class="page-logo">
        			<a href="index.php">
        			<h2><img src="<?php echo $this->basePath('assets/admin/layout/img/ew.png'); ?>" style="width:25px;vertical-align: bottom"> Energy<span>web</span></h2>
        			</a>
        			<div class="menu-toggler sidebar-toggler hide">
        			</div>
        		</div>
        		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
        		</a>
        		<div class="top-menu">
        			<ul class="nav navbar-nav pull-right">
        				<li class="dropdown dropdown-user">
        					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        					<img alt="" class="img-circle" src="<?php 
        					if(!$this->HeaderValue()->immagine()){
        					   echo $this->basePath('/assets/admin/layout/img/avatar.jpg');
        					}else{
        					   echo $this->basePath('../'.$this->HeaderValue()->immagine());
        					}
        					?>"/>
        					<span class="username username-hide-on-mobile">
        					<?php echo $this->HeaderValue()->nome(); ?> </span>
        					
        					<i class="fa fa-angle-down"></i>
        					</a>
        					<ul class="dropdown-menu dropdown-menu-default">
        						<li>
        							<a href="<?php echo $this->url('admin', array('controller' => 'utenti', 'action' => 'editar', 'id'=>$this->HeaderValue()->id())) ?>">
        							<i class="fa fa-user"></i> Profilo</a>
        						</li>
        						
        						
        						<li class="divider">
        						</li>
        						<li>
        							<a href="<?php echo $this->url('admin', array('controller' => 'login', 'action' => 'logout')) ?>">
        							<i class="fa fa-sign-out"></i> Esci</a>
        						</li>
        					</ul>
        				</li>
        			</ul>
        		</div>
        	</div>
        </div>
       
      <div class="clearfix">
</div> 
