<div class="page-content-wrapper">
		<div class="page-content">

			<div class="page-bar">
				<ul class="page-breadcrumb">
					<li>
						<i class="fa fa-th"></i>
						<a href="#"><?php echo $this->titulo;?></a>
						<i class="fa fa-angle-right"></i>
					</li>
					
					<?php if($this->titulo1 !== null):?>
					<li>
					Cerca Posterlab
					<i class="fa fa-angle-right"></i>
					</li>
					
					<li>
					<?php echo $this->titulo1; ?>
					<i class="fa fa-angle-right"></i>
					</li>
					
					<li>
					<?php echo $this->titulos; ?>
					</li>
					<?php endif;?>
					
				</ul>
			</div>
			<div class="row">
			
				<div class="col-md-12">
					<div class="col-md-6 pull-right no-padding">
						<a href="<?php echo $this->basePath() ?>/admin/contenuti/crear" class="btn grey-cascade pull-right">Aggiungi nuovo <i class="fa fa-plus white"></i></a>
					</div>
					<div class="col-md-6 pull-left no-padding">
					   <?php

                        // within a view script 
                        $form = $this->form; 
                        $form->prepare();
                        $form->setAttribute('action', $this->url('admin', array(
                            'controller' => 'contenuti',
                            'action' => 'cerca'
                        )));
                        
                        $form->setAttribute('method', 'post'); 
                        // Get the form label plugin
                        $formLabel = $this->plugin('formLabel');
                        // Render the opening tag
                        echo $this->form()->openTag($form);
                        
                        
                        ?>
                        
                        <div class="col-md-4 nopadding">
                            <div class="input-group">
                                <?php $posterlab = $form->get('posterlab'); ?>
                                <?php echo $formLabel->closeTag();?>							
                                <?php 				
                                     echo $this->formSelect($posterlab);
                                     echo '<small class="label  label-danger">'.$this->formElementErrors($posterlab).'</small>';
                                     ?>
                        		<span class="input-group-addon nopadding">
                        		  <?php echo $this->formElement($form->get('send')) ?> 
                        		</span>
                        											
                        	</div>
                        </div>	
                        <?php echo $this->form()->closeTag() ?>
                    </div>


                    <div class=" table-responsive col-md-12 nopadding">
                    
                    <table class="table table-striped table-hover dataTable no-footer" role="grid" id="sample_2" role="grid" aria-describedby="sample_2_info">
                            <thead>
                                <tr class="heading">
                       
                                    <th class="cien"><?php echo $this->tablaid; ?></th>
                                    <th><?php echo $this->tablanombre; ?></th>
                                    <th><?php echo $this->tablaposterlab; ?></th>
                                    <th><?php echo $this->posicion; ?></th>
                                    <th><?php echo $this->tablastato; ?></th>
                                    
                        </thead>
                            <tbody>
                                
                        <?php 
                     
                        foreach ($this->usuarios as $usuario):
                    
                        ?>
                            <tr role="row" class="odd edit">
                               
                                <td><?php echo $usuario->getId() ?> </td>
                                
                                <td class="sorting_1">
                                    <p class="titolo"><?php echo $usuario->getTitolo() ?></p>
                                    <div class="row-actions">
                                        <span><a href="<?php echo $this->basePath() ?>/admin/contenuti/editar/<?php echo $usuario->getId() ?>"><?php echo $this->tablamodifica; ?></a> | </span>
                                        <span><a onclick="return confirm('Vuoi eliminare a <?php echo $usuario->getTitolo() ?>?');" href="<?php echo $this->basePath() ?>/admin/contenuti/eliminar/<?php echo $usuario->getId() ?>"><?php echo $this->tablaelimina; ?></a> | </span>
                                        <span><a href="<?php echo $this->basePath() ?>/admin/contenuti/ver/<?php echo $usuario->getId() ?>"><?php echo $this->placever; ?></a></span>
                                    </div>
                                </td>
                                <td>
                                    <p class="titolo">
                                    <?php if($this->titulo1 !== null):?>
                                    <?php echo $this->titulo1; ?>
                                    <?php else:?>
                                     <?php echo $usuario->getPosterlab()->getTitolo(); ?>
                                    <?php endif;?></p>
                                </td>
                                <td>
                                    <?php echo $usuario->getPosizione(); ?>
                                </td>
                               
                                <td><?php if($usuario->getStato() == 1){echo '<span class="label fleft label-sm label-success">Attivato</span>';
                                }else{
                                    echo '<span class="label fleft label-sm label-danger">Disattivato</span>';} ?></td>
                                
                                
                            </tr>
                        <?php 
                      
                        endforeach; ?>
                    
                        <?php
                        $this->cycle()->assign(array("#F0F0F0", "#FFFFFF"));
                        $this->cycle()->prev();
                        ?>
                    </table>
                    </div>
            </div>
        </div>
    </div>
</div>