<div class="page-content-wrapper">
	<div class="page-content">


		<div class="page-bar">
			<ul class="page-breadcrumb">
				<li><i class="fa fa-university"></i> <a
					href="<?php echo $this->basePath() ?>/admin/contenuti/index"><?php echo $this->sezione; ?></a>
					<i class="fa fa-angle-right"></i></li>
				<li><a href="#"><?php echo $this->titulo; ?></a> <i
					class="fa fa-angle-right"></i></li>
			</ul>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="col-md-6 left pull-left no-padding">
					<a href="<?php echo $this->basePath() ?>/admin/contenuti/index"
						class="btn grey-cascade pull-left"><i class="fa fa-angle-left "></i> <?php echo $this->volver; ?> </a>
				</div>
			</div>
		</div>

<div class="col-md-12"><br></div>

     <div class="row">
		<div class="col-md-12">
			<div class="portlet box grey-cascade">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-university"></i>Dettaglio Contenuto
					</div>
					<div class="tools">
						<a href="javascript:;" class="collapse" data-original-title=""
							title=""> </a> <a href="#portlet-config" data-toggle="modal"
							class="config" data-original-title="" title=""> </a> <a
							href="javascript:;" class="reload" data-original-title=""
							title=""> </a> <a href="javascript:;" class="remove"
							data-original-title="" title=""> </a>
					</div>
				</div>
			
			<div class="portlet-body">
			
<?php if ($this->usuario !== null): ?>
		
		<div class="row">
			<div class="col-md-12"><h1><?php echo $this->usuario->getTitolo()?></h1></div>
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-8 profile-info">
						
						
						
						<ul class="dropdown-menu-list scroller">
							<li>Posterlab:<i class="fa fa-microphone"></i> <?php echo $this->usuario->getPosterlab()->getTitolo(); ?></li>
							<li><br></li>
							<li>Posizione: <i class="fa fa-clock-o"></i>  <?php echo $this->usuario->getPosizione()?> </li>
							<li><br></li>
							<li>Tipo: <i class="fa  fa-lock"></i>  http://<?php echo $this->usuario->getTipo()?> </li>
							<li><br></li>
							<li>
    						Stato:
    						<?php
                                if ($this->usuario->getStato() == 1) {
                                    echo '<span class="label fleft label-sm label-success">Attivato</span>';
                                } else {
                                    echo '<span class="label fleft label-sm label-danger">Disattivato</span>';
                                }
                                ?>
    						</li>
    						<li><br></li>
						</ul>
						
						<p>
						<a href="<?php echo $this->basePath() ?>/admin/contenuti/editar/<?php echo $this->usuario->getId();?>" class="btn green-sharp pull-left"> Modifica </a>
						</p>
					</div>
					<!--end col-md-8-->
					<div class="col-md-4">
						
					</div>
					<!--end col-md-4-->
				</div>
				<!--end row-->
                    
			</div>
			<div class="col-md-6">
			     <ul class="dropdown-menu-list scroller">
			     <li><span class="leftf">Contenuto: <i class="fa fa-bookmark"></i></span> <?php echo $this->usuario->getContenuto()?></li>
			     </ul>
			</div>
		</div>

		
    
<?php 
else: ?>
    <h4>Posterlab non trovato</h4>
<?php endif; ?>

</div>
	</div>
</div>
</div>
</div>
</div>



