<div class="large-4 columns large-offset-4">
<?php
// within a view script 
$form = $this->form; 
$form->prepare();
$form->setAttribute('action', $this->url('usuarios', array(
    'controller' => 'index',
    'action' => 'autenticar'
)));
$form->setAttribute('method', 'post'); 
// Get the form label plugin
$formLabel = $this->plugin('formLabel');
// Render the opening tag
echo $this->form()->openTag($form);
?>
<div class="form_element">
<?php
$email = $form->get('email');
echo $formLabel->openTag() . $email->getOption('label');
echo $formLabel->closeTag();
echo $this->formInput($email);
echo $this->formElementErrors($email);
?></div>
<div class="form_element">
    <?php
    $password = $form->get('clave');
    echo $formLabel->openTag() . $password->getOption('label');
    echo $formLabel->closeTag();
    echo $this->formInput($password);
    echo $this->formElementErrors($password);
    ?></div>
<?php echo $this->formElement($form->get('send')) ?> 
<?php echo $this->form()->closeTag() ?>
</div>