<?php /*?> 
<!-- BEGIN FOOTER -->
    <div class="page-footer">
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12 nopadding">
    		<div class="details" style="color:#FFF;">
    		<div class="inlineblock"><i class="fa fa-weixin px48"></i></div>
    			<div class="desc px18 inlineblock">
				    Partecipa
				</div>
				<div class="number px25 centrado">
				    <?php echo $this->password; ?>
			    </div>
		    </div>
        </div>
    	<div class="logo-footer"></div>
    
    	<div class="scroll-to-top">
    		<i class="icon-arrow-up"></i>
    	</div>
    </div>
   
<div class="col-md-12">
<footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php */ ?>
 
 
  </section>

  <a class="exit-off-canvas"></a>

  </div>
</div>