
<div class="off-canvas-wrap h100" data-offcanvas>
  <div class="inner-wrap h100">
    <nav class="tab-bar absolute cien top20">
      <section class="left-small">
        <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>

      <section class="middle tab-bar-section">
        <h1 class="title"></h1>
      </section>

      <section class="right-small">
        <div class="content-timer"><i class="fa fa-clock-o"></i><div id="my-timer"></div></div>
      </section>
    </nav>

    