
<div class="large-12 columns">
<h3><?php echo $this->titulo; ?></h3>
</div>
<div class="large-12 columns"><br></div>
<?php 

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('usuarios', array('controller' => 'estudiante', 'action' => 'registrar')));
$form->setAttribute('method', 'post');
//$form->setAttribute('data-abide', 'data-abide');

$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);

?>
<div class="large-4 columns">
<div class="name-field">
<?php 
$username = $form->get('username');
echo $formLabel->openTag() . $username->getOption('label').' <small>Campo Obligatorio</small>';
echo $this->forminput($username);
echo $formLabel->closeTag();
echo '<small class="error">'.$this->formelementerrors($username).'</small>';
?>
</div>


<div class="name-field">
<?php 
$direccion = $form->get('direccion');
echo $formLabel->openTag() . $direccion->getOption('label').' <small>Campo Obligatorio</small>';
echo $this->forminput($direccion);
echo $formLabel->closeTag();
echo '<small class="error">'.$this->formelementerrors($direccion).'</small>';
?>
</div>

<div class="name-field">
<?php 
$password = $form->get('password');
echo $formLabel->openTag() . $password->getOption('label').' <small>Campo Obligatorio</small>';
echo $this->forminput($password);
echo $formLabel->closeTag();
echo '<small class="error">'.$this->formelementerrors($password).'</small>';
?>
</div>

<div class="name-field">
<?php 
$confirmarPassword = $form->get('confirmarPassword');
echo $formLabel->openTag() . $confirmarPassword->getLabel().' <small>Campo Obligatorio</small>';
echo $this->forminput($confirmarPassword);
echo $formLabel->closeTag();
echo '<small class="error">'.$this->formelementerrors($confirmarPassword).'</small>';
?>
</div>

<div class="name-field">
<?php 
$recibeNewsletter = $form->get('recibeNewsletter');
echo $formLabel->openTag() . $recibeNewsletter->getLabel();
echo $formLabel->closeTag();
echo $this->formCheckbox($recibeNewsletter);
echo $this->formelementerrors($recibeNewsletter);
?>
</div>
</div>
<div class="large-2 columns">
<div class="name-field">
<?php 
$temas = $form->get('temas');
echo $formLabel->openTag() . $temas->getLabel().' <br><small>Campo Obligatorio</small>';
echo $this->formMultiCheckbox($temas);
echo $formLabel->closeTag();
echo '<small class="error">'.$this->formelementerrors($temas).'</small>';
?>
</div>

<div class="name-field">
<?php 
$genero = $form->get('genero');
echo $formLabel->openTag() . $genero->getLabel();
echo $formLabel->closeTag();
echo $this->formRadio($genero);
echo $this->formelementerrors($genero);
?>
</div>
</div>
<div class="large-2 columns">
<div class="name-field">
<?php 
$numeroFavorito = $form->get('numeroFavorito');
echo $formLabel->openTag() . $numeroFavorito->getLabel().' <br><small>Campo Obligatorio</small>';
echo $formLabel->closeTag();
echo $this->formRadio($numeroFavorito);
echo '<small class="error">'.$this->formelementerrors($numeroFavorito).'</small>';
?>
</div>
</div>
<div class="large-4 columns">

<div class="name-field">
<?php 
$pais = $form->get('pais');
echo $formLabel->openTag() . $pais->getLabel().' <small>Campo Obligatorio</small>';
echo $this->formSelect($pais);
echo $formLabel->closeTag();
echo '<small class="error">'.$this->formelementerrors($pais).'</small>';
?>
</div>

<div class="name-field">
<?php 
$experienciaZend = $form->get('experienciaZend');
echo $formLabel->openTag() . $experienciaZend->getLabel();
echo $formLabel->closeTag();
echo $this->formSelect($experienciaZend);
echo $this->formelementerrors($experienciaZend);
?>
</div>

<?php echo $this->formhidden($form->get('valorSecreto')); ?>
<?php echo $this->formelement($form->get('send')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>