<h3><?php echo $this->titulo; ?></h3>

<table>
    <tr>
        <td>Nombre:</td>
        <td><?php echo $this->estudiante->getNombre(); ?></td>
    </tr>
    <tr>
        <td>Apellido:</td>
        <td><?php echo $this->estudiante->getApellido(); ?></td>
    </tr>
    <tr>
        <td>Email:</td>
        <td><?php echo $this->estudiante->getEmail(); ?></td>
    </tr>
    <tr>
        <td>Password:</td>
        <td><?php echo $this->estudiante->getClave(); ?></td>
    </tr>
    <tr>
        <td>Confirma Password:</td>
        <td><?php echo $this->estudiante->getClave(); ?></td>
    </tr>
     
    
    
</table>