<div class="page-content-wrapper">
		<div class="page-content">        
			<div class="page-bar ">
				<ul class="page-breadcrumb ">
					<li>
						<i class="fa fa-users"></i>
						<a href="#"><?php echo $this->titulo; ?></a>
						<i class="fa fa-angle-right"></i>
					</li>
					
				</ul>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-6 pull-right no-padding">
						<a href="<?php echo $this->basePath() ?>/admin/utenti/crear" class="btn blue-steel pull-right">Aggiungi nuovo <i class="fa fa-plus white"></i></a>
					</div>


<div class=" table-responsive col-md-12 nopadding">
<table class="table table-striped table-hover dataTable no-footer" role="grid" id="sample_2" role="grid" aria-describedby="sample_2_info">
        <thead>
            <tr class="heading">
   
                <th class="cien"><?php echo $this->tablaid; ?></th>
                <th><?php echo $this->tablanombre; ?></th>
                <th><?php echo $this->tablastato; ?></th>
                <th><?php echo $this->tablamodifica; ?></th>
                <th><?php echo $this->tablaelimina; ?></th>
                <th><?php echo $this->tabladetalle; ?></th>
    </thead>
        <tbody>
            
    <?php foreach ($this->usuarios as $usuario): ?>
        <tr role="row" class="odd edit">
           
            <td><?php echo $usuario->getId() ?></td>
            <td class="sorting_1">
            <p class="titolo"><?php echo $usuario->getNome() ?></p>
                	<div class="row-actions">
                	<span><a href="<?php echo $this->basePath() ?>/admin/utenti/editar/<?php echo $usuario->getId() ?>"><?php echo $this->tablamodifica; ?></a> | </span>
                	<span><a onclick="return confirm('Vuoi eliminare a <?php echo $usuario->getNome() ?>?');" href="<?php echo $this->basePath() ?>/admin/utenti/eliminar/<?php echo $usuario->getId() ?>"><?php echo $this->tablaelimina; ?></a> | </span>
                	<span><a href="<?php echo $this->basePath() ?>/admin/utenti/ver/<?php echo $usuario->getId() ?>"><?php echo $this->placever; ?></a></span>
                	</div>
            </td>
            <td><?php if($usuario->getStato() == 1){echo '<span class="label fleft label-sm label-success">Attivato</span>';
            }else{
                echo '<span class="label fleft label-sm label-danger">Disattivato</span>';} ?></td>
            <td>
                <a href="<?php echo $this->basePath() ?>/admin/utenti/editar/<?php echo $usuario->getId() ?>" class="button tiny secondary"><?php echo $this->tablamodifica; ?></a>
            </td>
            <td>
                <a onclick="return confirm('Vuoi eliminare a <?php echo $usuario->getNome() ?>?');" href="<?php echo $this->basePath() ?>/admin/utenti/eliminar/<?php echo $usuario->getId() ?>" class="button tiny alert"><?php echo $this->tablaelimina; ?></a>
            </td>
            <td>
                <a href="<?php echo $this->basePath() ?>/admin/utenti/ver/<?php echo $usuario->getId() ?>" class="button tiny"><?php echo $this->placever; ?></a>
            </td>
        </tr>
    <?php endforeach; ?>

    <?php
    $this->cycle()->assign(array("#F0F0F0", "#FFFFFF"));
    $this->cycle()->prev();
    ?>
</table>
</div>
</div>
</div>
</div>
</div>