<h3><?php echo $this->titulo; ?></h3>

<table>
    <tr>
        <td>User Name:</td>
        <td><?php echo $this->estudiante->getUsername(); ?></td>
    </tr>
    <tr>
        <td>Direccion:</td>
        <td><?php echo $this->estudiante->getDireccion(); ?></td>
    </tr>
    <tr>
        <td>Password:</td>
        <td><?php echo $this->estudiante->getPassword(); ?></td>
    </tr>
    <tr>
        <td>Confirma Password:</td>
        <td><?php echo $this->estudiante->getConfirmarPassword(); ?></td>
    </tr>
     <tr>
        <td>Recibe Newsletter:</td>
        <td><?php echo $this->estudiante->getRecibeNewsletter(); ?></td>
    </tr>
    <tr>
        <td>Temas favoritos:</td>
        <td><?php foreach($this->estudiante->getTemas() as $tema): ?>
                <?php echo $tema; ?>
            <?php endforeach;?>
        </td>
    </tr>
    <tr>
        <td>Genero:</td>
        <td><?php echo $this->estudiante->getGenero(); ?></td>
    </tr>
    <tr>
        <td>Numero Favorito:</td>
        <td><?php echo $this->estudiante->getNumeroFavorito(); ?></td>
    </tr>
    <tr>
        <td>Pais:</td>
        <td><?php echo $this->estudiante->getPais(); ?></td>
    </tr>
    <tr>
        <td>Habilidades Zend:</td>
        <td><?php foreach($this->estudiante->getExperienciaZend() as $exp): ?>
                <?php echo $exp; ?>
            <?php endforeach;?>
        </td>
    </tr>
     <tr>
        <td>Valor Secreto:</td>
        <td><?php echo $this->estudiante->getValorSecreto(); ?></td>
    </tr>
</table>